updated many content based on the origin spec file of the postgresql 9.6

diff --git a/SOURCES/pgxl95-setup b/SOURCES/pgxl95-setup
--- a/SOURCES/pgxl95-setup
+++ b/SOURCES/pgxl95-setup
@@ -1,42 +1,121 @@
 #!/bin/sh
 #
 # pgxlsetup	Initialization and upgrade operations for pgxl
+#
+# PGVERSION is the full package version, e.g., 9.0.2
+# Note: the specfile inserts the correct value during package build
+PGVERSION=xxxx
+# PGMAJORVERSION is major version, e.g., 9.5 (this should match PG_VERSION)
+PGMAJORVERSION=`echo "$PGVERSION" | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/'`
+# PGENGINE is the directory containing the postmaster executable
+# Note: the specfile inserts the correct value during package build
+PGENGINE=xxxx
+# PREVMAJORVERSION is the previous major version, e.g., 9.3, for upgrades
+PREVMAJORVERSION=9.5
+# PREVPGENGINE is the directory containing the previous postmaster executable
+PREVPGENGINE=/usr/pgxl-$PREVMAJORVERSION/bin
 
-# PGXCVERSION is the full package version, e.g., 9.0.2
-# Note: the specfile inserts the correct value during package build
-PGXCVERSION=xxxx
-# PGXCENGINE is the directory containing the postmaster executable
-# Note: the specfile inserts the correct value during package build
-PGXCENGINE=xxxx
 
 # Absorb configuration settings from the specified systemd service file,
 # or the default "pgxl" service if not specified
 SERVICE_NAME="$2"
 if [ x"$SERVICE_NAME" = x ]
 then
-    SERVICE_NAME=pgxl9.5
+    SERVICE_NAME=pgxl-$PGMAJORVERSION
 fi
+
+# The third parameter is the old database version, i.e. $PREVMAJORVERSION in this case.
+# Use  "postgresql-$PREVMAJORVERSION" service, if not specified.
+OLD_SERVICE_NAME="$3"
+if [ x"$OLD_SERVICE_NAME" = x ]
+then
+    OLD_SERVICE_NAME=postgresql-$PREVMAJORVERSION
+fi
+
+USAGE_STRING=$"
+Usage: $0 {initdb|upgrade} [SERVICE_NAME]
+
+Script is aimed to help sysadmin with basic database cluster administration.
+
+The SERVICE_NAME is used for selection of proper unit configuration file; For
+more info and howto/when use this script please look at the docu file
+$README_RPM_DIST.  The 'pgxl'
+string is used when no SERVICE_NAME is explicitly passed.
+
+Available operation mode:
+  initdb        Create a new PostgreSQL database cluster.  This is usually the
+                first action you perform after PostgreSQL server installation.
+  upgrade       Upgrade PostgreSQL database cluster to be usable with new
+                server.  Use this if you upgraded your PostgreSQL server to
+                newer major version (currently from $PREVMAJORVERSION \
+to $PGMAJORVERSION).
+
+Environment:
+  PGSETUP_INITDB_OPTIONS     Options carried by this variable are passed to
+                             subsequent call of \`initdb\` binary (see man
+                             initdb(1)).  This variable is used also during
+                             'upgrade' mode because the new cluster is actually
+                             re-initialized from the old one.
+  PGSETUP_PGUPGRADE_OPTIONS  Options in this variable are passed next to the
+                             subsequent call of \`pg_upgrade\`.  For more info
+                             about possible options please look at man
+                             pg_upgrade(1).
+  PGSETUP_DEBUG              Set to '1' if you want to see debugging output."
+
+# note that these options are useful at least for help2man processing
+case "$1" in
+    --version)
+        echo "psxl$PGMAJORVERSION-setup $PGVERSION"
+        exit 0
+        ;;
+    --help|--usage)
+        echo "$USAGE_STRING"
+        exit 0
+        ;;
+esac
 
 if [ -f "/etc/init.d/${SERVICE_NAME}.service" ]
 then
     SERVICE_FILE="/etc/init.d/${SERVICE_NAME}.service"
-##elif [ -f "/lib/systemd/system/${SERVICE_NAME}.service" ]
-##then
-##    SERVICE_FILE="/lib/systemd/system/${SERVICE_NAME}.service"
+elif [ -f "/lib/systemd/system/${SERVICE_NAME}.service" ]
+then
+    SERVICE_FILE="/lib/systemd/system/${SERVICE_NAME}.service"
 else
     echo "Could not find systemd unit file ${SERVICE_NAME}.service"
     exit 1
 fi
 
 # Get port number and data directory from the service file
-PGXCPORT=`sed -n 's/Environment=PGXCPORT=//p' "${SERVICE_FILE}"`
-PGXCDATA=`sed -n 's/Environment=PGXCDATA=//p' "${SERVICE_FILE}"`
+#PGPORT=`sed -n 's/Environment=PGPORT=//p' "${SERVICE_FILE}"`
+#PGDATA=`sed -n 's/Environment=PGDATA=//p' "${SERVICE_FILE}"`
 
+# this parsing technique fails for PGPORT pathnames containing spaces,
+# but there's not much I can do about it given systemctl's output format...
+PGPORT=`systemctl show -p Environment "${SERVICE_NAME}.service" |
+                sed 's/^Environment=//' | tr ' ' '\n' |
+                sed -n 's/^PGPORT=//p' | tail -n 1`
+if [ x"$PGPORT" = x ]; then
+    echo "failed to find PGPORT setting in ${SERVICE_NAME}.service"
+    exit 1
+fi
+
+# this parsing technique fails for PGDATA pathnames containing spaces,
+# but there's not much I can do about it given systemctl's output format...
+PGDATA=`systemctl show -p Environment "${SERVICE_NAME}.service" |
+                sed 's/^Environment=//' | tr ' ' '\n' |
+                sed -n 's/^PGDATA=//p' | tail -n 1`
+if [ x"$PGDATA" = x ]; then
+    echo "failed to find PGDATA setting in ${SERVICE_NAME}.service"
+    exit 1
+fi
+
+# Log file for pg_upgrade
+PGUPLOG=/var/lib/pgxl/$PGMAJORVERSION/pgupgrade.log
 # Log file for initdb
-PGLOG=/var/lib/pgxl/9.5/initdb.log
+PGLOG=/var/lib/pgxl/$PGMAJORVERSION/initdb.log
 
-export PGXCPORT
-export PGXCDATA
+export PGPORT
+export PGDATA
 
 # For SELinux we need to use 'runuser' not 'su'
 if [ -x /sbin/runuser ]
@@ -50,33 +129,34 @@ script_result=0
 
 # code shared between initdb and upgrade actions
 perform_initdb(){
-	if [ ! -e "$PGXCDATA" -a ! -h "$PGXCDATA" ]
-	then
-		mkdir -p "$PGXCDATA" || return 1
-		chown pgxl:pgxl "$PGXCDATA"
-		chmod go-rwx "$PGXCDATA"
+	if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ];then
+		mkdir -p "$PGDATA" || return 1
+		chown postgres:postgres "$PGDATA"
+		chmod go-rwx "$PGDATA"
 	fi
-	# Clean up SELinux tagging for PGXCDATA
-	[ -x /sbin/restorecon ] && /sbin/restorecon "$PGXCDATA"
+	# Clean up SELinux tagging for PGDATA
+	[ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
 
 	# Create the initdb log file if needed
-	if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
-	then
+	if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ];then
 		touch "$PGLOG" || return 1
-		chown pgxl:pgxl "$PGLOG"
+		chown postgres:postgres "$PGLOG"
 		chmod go-rwx "$PGLOG"
 		[ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
 	fi
 
 	# Initialize the database
-	$SU -l pgxl -c "$PGXCENGINE/initdb --PGXCDATA='$PGXCDATA' --auth='ident'" >> "$PGLOG" 2>&1 < /dev/null
+  initdbcmd="$PGENGINE/initdb --pgdata='$PGDATA' --auth='ident'"
+  initdbcmd+=" $PGSETUP_INITDB_OPTIONS"
+
+	$SU -l postgres -c "$initdbcmd" >> "$PGLOG" 2>&1 < /dev/null
 
 	# Create directory for postmaster log files
-	mkdir "$PGXCDATA/pg_log"
-	chown pgxl:pgxl "$PGXCDATA/pg_log"
-	chmod go-rwx "$PGXCDATA/pg_log"
+	mkdir "$PGDATA/pg_log"
+	chown postgres:postgres" $PGDATA/pg_log"
+	chmod go-rwx "$PGDATA/pg_log"
 
-	if [ -f "$PGXCDATA/PG_VERSION" ]
+	if [ -f "$PGDATA/PG_VERSION" ]
 	then
 	    return 0
 	fi
@@ -84,90 +164,108 @@ perform_initdb(){
 }
 
 initdb(){
-    if [ -f "$PGXCDATA/PG_VERSION" ]
-    then
-	echo $"Data directory is not empty!"
-	echo
-	script_result=1
+    if [ -f "$PGDATA/PG_VERSION" ];then
+      echo $"Data directory is not empty!"
+      echo
+      script_result=1
     else
-	echo -n $"Initializing database ... "
-	if perform_initdb
-	then
-	    echo $"OK"
-	else
-	    echo $"failed, see $PGLOG"
-	    script_result=1
-	fi
-	echo
+      echo -n $"Initializing database ... "
+      if perform_initdb;then
+        echo $"OK"
+      else
+        echo $"failed, see $PGLOG"
+        script_result=1
+      fi
+      echo
     fi
 }
 
 upgrade(){
     # must see previous version in PG_VERSION
-    if [ ! -f "$PGXCDATA/PG_VERSION" -o \
-	 x`cat "$PGXCDATA/PG_VERSION"` != x"$PREVMAJORVERSION" ]
-    then
-	echo
-	echo $"Cannot upgrade because database is not of version $PREVMAJORVERSION."
-	echo
-	exit 1
+    if [ ! -f "$PGDATA/PG_VERSION" -o \
+	    x`cat "$PGDATA/PG_VERSION"` != x"$PREVMAJORVERSION" ];then
+      echo
+      echo $"Cannot upgrade because the database in $PGDATA is not of"
+      echo $"compatible previous version $PREVMAJORVERSION."
+      echo
+      exit 1
     fi
-    if [ ! -x "$PGXCENGINE/pg_upgrade" ]
-    then
-	echo
-	echo $"Please install the pgxlupgrade RPM."
-	echo
-	exit 5
+    if [ ! -x "$PGENGINE/pg_upgrade" ];then
+      echo
+      echo $"Could not find pg_upgrade binary"
+      echo
+      exit 5
     fi
 
     # Make sure service is stopped
     # Using service here makes it work both with systemd and other init systems
-    service "$SERVICE_NAME" stop
+    systemctl stop "$SERVICE_NAME"
 
     # Set up log file for pg_upgrade
     rm -f "$PGUPLOG"
     touch "$PGUPLOG" || exit 1
-    chown pgxl:pgxl "$PGUPLOG"
+    chown postgres:postgres "$PGUPLOG"
     chmod go-rwx "$PGUPLOG"
     [ -x /sbin/restorecon ] && /sbin/restorecon "$PGUPLOG"
 
-    # Move old DB to PGXCDATAOLD
-    PGXCDATAOLD="${PGXCDATA}-old"
-    rm -rf "$PGXCDATAOLD"
-    mv "$PGXCDATA" "$PGXCDATAOLD" || exit 1
+    # Move old DB to PGDATAOLD
+    PGDATAOLD="${PGDATA}-old"
+    rm -rf "$PGDATAOLD"
+    mv "$PGDATA" "$PGDATAOLD" || exit 1
+
+# TODO 
+    # Create configuration file for upgrade process
+#    HBA_CONF_BACKUP="$PGDATAOLD/pg_hba.conf.postgresql-setup.`date +%s`"
+#    HBA_CONF_BACKUP_EXISTS=0
+#
+#    if [ ! -f $HBA_CONF_BACKUP ]; then
+#        mv "$PGDATAOLD/pg_hba.conf" "$HBA_CONF_BACKUP"
+#        HBA_CONF_BACKUP_EXISTS=1
+#
+#        # For fluent upgrade 'postgres' user should be able to connect
+#        # to any database without password.  Temporarily, no other type
+#        # of connection is needed.
+#        echo "local all postgres ident" > "$PGDATAOLD/pg_hba.conf"
+#    fi
 
     echo -n $"Upgrading database: "
 
     # Create empty new-format database
-    if perform_initdb
-    then
-	# Do the upgrade
-	$SU -l pgxl -c "$PGXCENGINE/pg_upgrade \
-		'--old-bindir=$PREVPGXCENGINE' \
-		'--new-bindir=$PGXCENGINE' \
-		'--old-datadir=$PGXCDATAOLD' \
-		'--new-datadir=$PGXCDATA' \
-		--link \
-		'--old-port=$PGXCPORT' '--new-port=$PGXCPORT' \
-		--user=pgxl" >> "$PGUPLOG" 2>&1 < /dev/null
-	if [ $? -ne 0 ]
-	then
-	    # pg_upgrade failed
-	    script_result=1
-	fi
+    if perform_initdb;then
+      # Do the upgrade
+      $SU -l postgres -c "$PGENGINE/pg_upgrade \
+        '--old-bindir=$PREVPGENGINE' \
+        '--new-bindir=$PGENGINE' \
+        '--old-datadir=$PGDATAOLD' \
+        '--new-datadir=$PGDATA' \
+        --link \
+        '--old-port=$PGPORT' '--new-port=$PGPORT' \
+        --user=postgres" >> "$PGUPLOG" 2>&1 < /dev/null
+      if [ $? -ne 0 ];then
+        # pg_upgrade failed
+        script_result=1
+      fi
     else
-	# initdb failed
-	script_result=1
+      # initdb failed
+      script_result=1
     fi
 
-    if [ $script_result -eq 0 ]
-    then
+# TODO
+    # Move back the backed-up pg_hba.conf regardless of the script_result.
+#    if [ x$HBA_CONF_BACKUP_EXISTS = x1 ]; then
+#        mv -f "$HBA_CONF_BACKUP" "$PGDATAOLD/pg_hba.conf"
+#    fi
+
+    if [ $script_result -eq 0 ];then
 	    echo $"OK"
+      echo
+      echo $"The configuration files were replaced by default configuration."
+      echo $"The previous configuration and data are stored in folder"
+      echo $PGDATAOLD.
     else
 	    # Clean up after failure
-	    rm -rf "$PGXCDATA"
-	    mv "$PGXCDATAOLD" "$PGXCDATA"
-
+	    rm -rf "$PGDATA"
+	    mv "$PGDATAOLD" "$PGDATA"
 	    echo $"failed"
     fi
     echo
@@ -177,14 +275,14 @@ upgrade(){
 # See how we were called.
 case "$1" in
   initdb)
-	initdb
-	;;
+    initdb
+    ;;
   upgrade)
-	upgrade
-	;;
+    upgrade
+    ;;
   *)
-	echo $"Usage: $0 {initdb|upgrade} [ service_name ]"
-	exit 2
+    echo $"Usage: $0 {initdb|upgrade} [ service_name ]"
+    exit 2
 esac
 
 exit $script_result
